[package]
# طين is an arabic word for Clay
name = "tin"
version = "0.5.1"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["web-programming"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["boilerplate"]
license = "MIT"
publish = false
repository = "https://github.com/azzamsa/tin"
description = "Rust GraphQL Template"

[profile.release]
strip = true
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
axum = "0.6.19"
hyper = "0.14.27"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "5.0.10", features = ["uuid", "chrono"] }
async-graphql-axum = "5.0.10"

# Rest
utoipa = { version = "3.3.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1.4", features = ["axum"] }

# Database
sqlx = { version = "0.7.1", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "migrate"] }

# Logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "time", "local-time"] }

# Configurations
dotenv = "0.15.0"

# Misc
base64 = "0.21.2"
chrono = "0.4.26"
frunk = "0.4.2"
frunk_core = { version = "0.4.2" }
serde = "1.0.171"
serde_json = "1.0.103"
thiserror = "1.0.43"
time = "0.3.23"
ulid = { version = "1.0.0", features = ["uuid"] }
url = "2.4.0"
uuid = "1.4.1"

[dev-dependencies]
anyhow = "1.0.72"
cynic = "3.2.2"
mime = "0.3.17"
tower = { version = "0.4.13", features = ["util"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version}-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.release]
tag-message = "v{{version}}"
pre-release-commit-message = "v{{version}}"
pre-release-hook = ["just", "_release-prepare", "{{version}}"]
