[package]
name = "nahla"
version = "0.1.0"
description = "A web service boilerplate in Rust"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2021"

[dependencies]
poem = { version = "1.2.45", features = ["test"] }
tokio = { version = "1.15.0", features = ["rt-multi-thread"] }

# GraphQL
async-graphql = { version = "3.0.25" }
async-graphql-poem = "3.0.25"

anyhow = "1.0.52"

# Database
sqlx = { version = "0.5", features = ["runtime-async-std-native-tls", "postgres", "offline"] }


# log
log = "0.4.14"
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4.19"
colored = "2.0.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
cynic = "1.0.0"
serde_json = "1.0.75"
