[package]
# طين is an arabic word for Clay
name = "tin"
version = "0.3.2"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["web-programming"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["boilerplate"]
license = "MIT"
repository = "https://github.com/azzamsa/tin"
description = "Rust GraphQL Template"

[dependencies]
axum = "0.6.18"
hyper = "0.14.26"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "5.0.10", features = ["uuid", "chrono"] }
async-graphql-axum = "5.0.10"

# Rest
utoipa = { version = "3.3.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1.3", features = ["axum"] }

# Database
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "postgres", "offline", "uuid", "chrono", "migrate"] }

# Logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "time", "local-time"] }

# Configurations
dotenv = "0.15.0"

base64 = "0.21.2"
chrono = "0.4.26"
serde = "1.0.164"
serde_json = "1.0.96"
thiserror = "1.0.40"
time = "0.3.22"
ulid = { version = "1.0.0", features = ["uuid"] }
url = "2.4.0"
uuid = "1.3.3"

[dev-dependencies]
anyhow = "1.0.71"
cynic = "3.0.2"
mime = "0.3.17"
tower = { version = "0.4.13", features = ["util"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version}-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
