[package]
# طين is an arabic word for Clay
name = "tin"
version = "0.3.2"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["web-programming"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["boilerplate"]
license = "MIT"
repository = "https://github.com/azzamsa/tin"
description = "Rust GraphQL Template"

[dependencies]
axum = "0.6.4"
hyper = "0.14.23"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "5.0.5", features = ["uuid", "chrono"] }
async-graphql-axum = "5.0.5"

# Rest
utoipa = { version = "3.0.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["axum"] }

# Database
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "offline", "uuid", "chrono", "migrate"] }

# Logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "time", "local-time"] }

# Configurations
dotenv = "0.15.0"

base64 = "0.21.0"
chrono = "0.4.23"
serde = "1.0.152"
serde_json = "1.0.91"
thiserror = "1.0.38"
time = "0.3.17"
ulid = { version = "1.0.0", features = ["uuid"] }
url = "2.3.1"
uuid = "1.2.2"

[dev-dependencies]
# git hooks
cargo-husky = { version = "1", features = ["user-hooks"] }

anyhow = "1.0.68"
cynic = "2.2.4"
mime = "0.3.16"
tower = { version = "0.4.13", features = ["util"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version}-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
