[package]
# طين is an arabic word for Clay
name = "tin"
version = "0.3.0"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["web-programming"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["boilerplate"]
license = "MIT"
repository = "https://github.com/azzamsa/tin"
description = "Rust GraphQL Template"

[dependencies]
axum = "0.6"
hyper = "0.14"
tokio = { version = "1.22", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "5.0", features = ["uuid", "chrono"] }
async-graphql-axum = "5.0"

# Rest
utoipa = { version = "2.4", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.0", features = ["axum"] }

# Database
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres", "offline", "uuid", "chrono", "migrate"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }

# Configurations
dotenv = "0.15"

base64 = "0.13"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
time = "0.3"
ulid = { version = "1.0", features = ["uuid"] }
url = "2.3"
uuid = "1.2"

[dev-dependencies]
# git hooks
cargo-husky = { version = "1", features = ["user-hooks"] }

anyhow = "1.0"
cynic = "2.2"
mime = "0.3"
tower = { version = "0.4", features = ["util"] }

# cross-rs configuration
[package.metadata.cross.target.x86_64-unknown-linux-gnu]
# The latest version of cross-rs doesn't include OpenSSL support
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
]
